spring.application.name=pi
spring.config.import=optional:file:.env[.properties]

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://db.prisma.io:5432/postgres?sslmode=require
spring.datasource.username=4c437869560e6c2774845a45df588ed087787042e88aec7fec22373d88cab686
spring.datasource.password=sk_OBiA5ixjGInP-UVq2BFrd
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
